---
title: "Working with Spatial Data in R"
editor: visual
---

## Setup

```{r}
# load in appropriate packages
library(readr)
library(here)
library(sf)
library(ggplot2)
library(leaflet)
library(scales)
library(ggspatial)
library(dplyr)
library(prettymapr)
```

## Exploring the Data

```{r}
# read in shapefile using read_sf()
ak_rgns_sf <- read_sf(here("data/ak_regions_simp.shp"))
```

```{r}
# quick plot
plot(ak_rgns_sf)
```

```{r}
# using various functions to view dataset variables:

# provides class types
class(ak_rgns_sf)

# provides geometric variable
head(ak_rgns_sf)

# provides variable overview
glimpse(ak_rgns_sf)
```

## Coordinate Reference System (CRS)

```{r}
# view set coordinate reference system
st_crs(ak_rgns_sf)
```

```{r}
# transform original geospatial data from one coordinate system to another
ak_rgns_3338_sf <- ak_rgns_sf %>%
    st_transform(crs = 3338)

st_crs(ak_rgns_3338_sf)
```

```{r}
# view updated plots
plot(ak_rgns_3338_sf)
```

## sf & Tidyverse

### Using select() function

```{r}
# returns the names of all the columns in dataset
colnames(ak_rgns_3338_sf)
```

```{r}
# view selected region variable + geometry column
ak_rgns_3338_sf %>%
    select(region)
```

### Using filter() function

```{r}
# view unique region variable
unique(ak_rgns_3338_sf$region)
```

```{r}
# view filtered southeast region
ak_rgns_3338_sf %>%
    filter(region == "Southeast")
```

## Spatial Joins

### Exercise 1

```{r}
# read in population data using read_csv() function
pop_df <- read_csv(here("data/alaska_population.csv"))
```

```{r}
# turn pop into a spatial object
pop_4326_sf <- st_as_sf(pop_df,
                        coords = c('lng', 'lat'),
                        crs = 4326,
                        remove = F)

head(pop_4326_sf)
```

```{r}
# join population data with Alaska regions data using st_join()

# to avoid error, we must use the st_transform() function
pop_3338_sf <- st_transform(pop_4326_sf, 
                            crs = 3338)

pop_joined_sf <- st_join(pop_3338_sf, 
                         ak_rgns_3338_sf, 
                         join = st_within)

head(pop_joined_sf)
```

```{r}
# calculate total population by region using group_by() and summarize() functions
pop_rgn_df <- pop_joined_sf %>%
    st_drop_geometry() %>%
    group_by(region) %>%
    summarize(total_pop = sum(population))

head(pop_rgn_df)
```

```{r}
# use left_join() function to regain region geometries
pop_rgn_3338_sf <- left_join(ak_rgns_3338_sf, 
                             pop_rgn_df, 
                             by = "region")

# check updated plot
plot(pop_rgn_3338_sf["total_pop"])
```

```{r}
# calculate population by management area instead of region
pop_mgmt_3338_sf <- pop_rgn_3338_sf %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop))

plot(pop_mgmt_3338_sf["total_pop"])
```

```{r}
# distinguish region geometries using do_union = F
pop_mgmt_3338_sf <- pop_rgn_3338_sf %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop), do_union = F)

plot(pop_mgmt_3338_sf["total_pop"])
```

```{r}
# save spatial object to new file using write_sf()
write_sf(pop_rgn_3338_sf, here("data/ak_regions_population.shp"))
```

## Visualizing with ggplot

```{r}
# plot sf object using geom_sf() function
ggplot(pop_rgn_3338_sf) +
    geom_sf(aes(fill = total_pop)) +
    labs(fill = "Total Population") +
    scale_fill_continuous(low = "khaki",
                          high =  "firebrick",
                          labels = comma) +
    theme_bw()
```

```{r}
# input multiple shapefiles into the same plot

# read in rivers shapefile
rivers_3338_sf <- read_sf(here("data/ak_rivers_simp.shp"))

# view crs
st_crs(rivers_3338_sf)
```

```{r}
# layer rivers shapefile over previous plot
ggplot() +
    geom_sf(data = pop_rgn_3338_sf, 
            aes(fill = total_pop)) +
    geom_sf(data = pop_3338_sf, 
            size = 0.5) +
    geom_sf(data = rivers_3338_sf,
            aes(linewidth = StrOrder)) +
    scale_linewidth(range = c(0.05, 0.5),
                    guide = "none") +
    labs(title = "Total Population by Alaska Region",
         fill = "Total Population") +
    scale_fill_continuous(low = "khaki",
                          high =  "firebrick",
                          labels = comma) +
    theme_bw() 
```

### Incorporate Base Maps Into Static Maps

```{r}
# assign st_transform() function to object
pop_3857_sf <- st_transform(pop_3338_sf, 
                         crs = 3857)
```

```{r}
# add ggspatial::annotate_map_tile() function into ggplot
ggplot(data = pop_3857_sf) +
    ggspatial::annotation_map_tile(type = "osm", zoom = 4, progress = 'none') + 
    # higher zoom values are more detailed 
    geom_sf(aes(color = population),
            fill = NA) +
    scale_color_continuous(low = "darkkhaki",
                           high =  "firebrick",
                           labels = comma)
```

## Visualizing sf Objects with Leaflet

```{r}
# define & save leaflet projection for Alaska Albers
epsg3338 <- leaflet::leafletCRS(
    crsClass = "L.Proj.CRS",
    code = "EPSG:3338",
    proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
    resolutions = 2 ^ (16:7)
)
```

```{r}
# use st_transorm() function to produce unprojected coordinate system
pop_rgn_4326_sf <- pop_rgn_3338_sf %>% 
    st_transform(crs = 4326)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
    addPolygons(data = pop_rgn_4326_sf,
                fillColor = "gray",
                weight = 1)

m
```

```{r}
# add labels, legends, and color scale
pal <- colorNumeric(palette = "Reds", domain = pop_rgn_4326_sf$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
    addPolygons(
        data = pop_rgn_4326_sf,
        fillColor = ~ pal(total_pop),
        weight = 1,
        color = "black",
        fillOpacity = 1,
        label = ~ region
    ) %>%
    addLegend(
        position = "bottomleft",
        pal = pal,
        values = range(pop_rgn_4326_sf$total_pop),
        title = "Total Population"
    )

m
```

```{r}
# add individual communities with pop-up populations!
pal <- colorNumeric(palette = "Reds", domain = pop_rgn_4326_sf$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
    addPolygons(
        data = pop_rgn_4326_sf,
        fillColor = ~ pal(total_pop),
        weight = 1,
        color = "black",
        fillOpacity = 1
    ) %>%
    addCircleMarkers(
        data = pop_4326_sf,
        lat = ~ lat,
        lng = ~ lng,
        radius = ~ log(population / 500),
        # arbitrary scaling
        fillColor = "gray",
        fillOpacity = 1,
        weight = 0.25,
        color = "black",
        label = ~ paste0(pop_4326_sf$city, ", population ", comma(pop_4326_sf$population))
    ) %>%
    addLegend(
        position = "bottomleft",
        pal = pal,
        values = range(pop_rgn_4326_sf$total_pop),
        title = "Total Population"
    )

m
```











